version: "3.9"

services:
  web:
    build: .
    image: flaviogf/skills-matrix
    environment:
      DATABASE_URL: postgres://root:root@db/skills_matrix
      LANG: en_US.UTF-8
      RACK_ENV: production
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: enabled
      RAILS_SERVE_STATIC_FILES: enabled
      SECRET_KEY_BASE: calopsita
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: skills_matrix
